// Agro-Weld — shared content: languages, UI strings (PL/EN/DE/RU/FR), categories, machine catalog.
const LANGS = [
  { code: 'pl', label: 'PL', name: 'Polski' },
  { code: 'en', label: 'EN', name: 'English' },
  { code: 'de', label: 'DE', name: 'Deutsch' },
  { code: 'ru', label: 'RU', name: 'Русский' },
  { code: 'fr', label: 'FR', name: 'Français' },
];

const UI = {
  pl: {
    nav: { home: 'Start', offer: 'Oferta', process: 'Proces', why: 'Dlaczego my', projects: 'Realizacje', contact: 'Kontakt' },
    cta: { askOffer: 'Zapytaj o ofertę', viewMachines: 'Zobacz maszyny', viewAll: 'Pełna oferta maszyn', learnMore: 'Dowiedz się więcej', downloadCatalog: 'Pobierz katalog (PDF)', backHome: 'Wróć na stronę główną', send: 'Wyślij zapytanie' },
    hero: {
      eyebrow: 'Producent maszyn i linii technologicznych',
      titleA: 'Maszyny i linie technologiczne', titleB: 'dla rolnictwa i przemysłu',
      sub: 'Agro-Weld projektuje i produkuje maszyny do obróbki warzyw i owoców oraz kompletne linie produkcyjne — od przyjęcia surowca po paletyzację. Konstrukcje dla gospodarstw, przetwórstwa i przemysłu.',
      s1n: '25+', s1l: 'rodzajów maszyn', s2n: '9', s2l: 'etapów linii', s3n: '100%', s3l: 'konfiguracji pod klienta',
    },
    process: { eyebrow: 'Jak to działa', title: 'Jedna linia, od pola do palety', sub: 'Każdy etap obróbki plonu obsługujemy własnymi maszynami. Łączymy je w modułowe, kompletne linie technologiczne.', note: 'Każdą maszynę i linię konfigurujemy pod rodzaj warzyw, skalę produkcji i układ hali.' },
    steps: [
      { name: 'Przyjęcie', desc: 'Wywrotnice skrzyniopalet i kosze przyjęciowe odbierają plon z przyczep i skrzyń.' },
      { name: 'Buforowanie', desc: 'Zasobniki buforowe utrzymują równy, ciągły przepływ towaru na linii.' },
      { name: 'Oczyszczanie', desc: 'Separatory i czyszczarki szczotkowe usuwają ziemię, kamienie i resztki.' },
      { name: 'Sortowanie', desc: 'Kalibrowniki i stoły selekcyjne dzielą towar według wielkości i jakości.' },
      { name: 'Ważenie', desc: 'Wagi kontrolne i liczarki zapewniają powtarzalność i dokładność porcji.' },
      { name: 'Pakowanie', desc: 'Wagoworkownice, raszlownice i napełniacze pakują gotowy produkt.' },
      { name: 'Paletyzacja', desc: 'Paletyzatory i formatory układają opakowania na palecie pod magazyn.' },
    ],
    why: {
      eyebrow: 'Dlaczego Agro-Weld', title: 'Maszyny, które rozwijają się razem z Tobą', sub: 'Stawiamy na praktyczne rozwiązania, trwałość i pełne dopasowanie do potrzeb klienta.',
      items: [
        { title: 'Autorskie konstrukcje', desc: 'Maszyny i linie projektowane od podstaw przez doświadczonych konstruktorów — dla rolnictwa i przemysłu.' },
        { title: 'Modyfikacje pod klienta', desc: 'Każdą maszynę dostosujemy do Twojej linii, rodzaju warzyw i układu hali.' },
        { title: 'Jakość i bezpieczeństwo', desc: 'Trwałe materiały, opcja stali nierdzewnej i sprawdzone systemy zabezpieczeń.' },
        { title: 'Kompletne linie', desc: 'Od przyjęcia po paletyzację — modułowo, pod każdą skalę produkcji.' },
      ],
    },
    featured: { eyebrow: 'Wybrane maszyny', title: 'Sprawdzone konstrukcje z naszej oferty', sub: 'Najczęściej wybierane maszyny do czyszczenia, sortowania i pakowania.' },
    catalog: { eyebrow: 'Pełna oferta', title: 'Maszyna na każdy etap produkcji', sub: 'Przeglądaj ofertę według etapu linii technologicznej.' },
    lines: { eyebrow: 'Linie produkcyjne', title: 'Kompletne linie pod klucz', body: 'Projektujemy i budujemy linie do oczyszczania, obróbki, sortowania i pakowania — dla gospodarstw, zakładów przetwórczych i przemysłu. Modułowa budowa pozwala rozwijać linię wraz ze wzrostem produkcji.', points: ['Modułowa, skalowalna budowa', 'Rolnictwo · przetwórstwo · przemysł', 'Wykonania INOX, automatyzacja i serwis'], cta: 'Porozmawiajmy o Twojej linii' },
    contact: {
      eyebrow: 'Kontakt', title: 'Zapytaj o ofertę', sub: 'Opisz, co chcesz przetwarzać i w jakiej skali — przygotujemy propozycję maszyny lub całej linii.',
      name: 'Imię i nazwisko', company: 'Firma / gospodarstwo', email: 'E-mail', phone: 'Telefon', message: 'Czego potrzebujesz?', submit: 'Wyślij zapytanie',
      infoTitle: 'Dane kontaktowe', addrL: 'Adres', phoneL: 'Telefon', emailL: 'E-mail', hoursL: 'Godziny pracy', hours: 'Pon.–Pt. 7:00–16:00', note: 'Zapytanie jest niezobowiązujące. Odpowiadamy zwykle w ciągu jednego dnia roboczego.',
    },
    footer: { tagline: 'Polski producent maszyn i linii technologicznych — czyszczenie, sortowanie, obróbka i pakowanie dla rolnictwa, przetwórstwa i przemysłu.', col1: 'Nawigacja', col2: 'Etapy linii', col3: 'Kontakt', rights: 'Wszelkie prawa zastrzeżone.' },
    offer: { eyebrow: 'Oferta', title: 'Katalog maszyn', sub: 'Pełen przegląd maszyn Agro-Weld, pogrupowany według etapu linii technologicznej.', count: 'maszyn' },
    product: { back: 'Wróć do oferty', specsTitle: 'Dane techniczne', featTitle: 'Najważniejsze cechy', optTitle: 'Wyposażenie i opcje', modelsTitle: 'Dostępne modele', inquiryTitle: 'Zainteresowany tą maszyną?', inquirySub: 'Skonfigurujemy ją pod Twój rodzaj warzyw i skalę produkcji.', related: 'Zobacz też', model: 'Model' },
  },
  en: {
    nav: { home: 'Home', offer: 'Machines', process: 'Process', why: 'Why us', projects: 'Lines', contact: 'Contact' },
    cta: { askOffer: 'Request a quote', viewMachines: 'View machines', viewAll: 'Full machine catalog', learnMore: 'Learn more', downloadCatalog: 'Download catalog (PDF)', backHome: 'Back to home', send: 'Send inquiry' },
    hero: {
      eyebrow: 'Manufacturer of processing machines & lines',
      titleA: 'Machines and processing lines', titleB: 'for agriculture and industry',
      sub: 'Agro-Weld designs and builds produce-handling machines and complete production lines — from reception to palletising. Engineered for farms, food processing and industry.',
      s1n: '25+', s1l: 'machine types', s2n: '9', s2l: 'line stages', s3n: '100%', s3l: 'built to order',
    },
    process: { eyebrow: 'How it works', title: 'One line, from field to pallet', sub: 'We cover every stage of crop processing with our own machines, combined into modular, complete lines.', note: 'Every machine and line is configured for your crop, production scale and floor layout.' },
    steps: [
      { name: 'Reception', desc: 'Pallet-box tippers and receiving hoppers take the crop from trailers and crates.' },
      { name: 'Buffering', desc: 'Buffer hoppers keep an even, continuous product flow along the line.' },
      { name: 'Cleaning', desc: 'Separators and brush cleaners remove soil, stones and residue.' },
      { name: 'Sorting', desc: 'Graders and sorting tables split produce by size and quality.' },
      { name: 'Weighing', desc: 'Checkweighers and counters ensure repeatable, accurate portions.' },
      { name: 'Packing', desc: 'Weigh-baggers, raschel baggers and fillers pack the finished product.' },
      { name: 'Palletising', desc: 'Palletisers and pallet formers stack packs ready for the warehouse.' },
    ],
    why: {
      eyebrow: 'Why Agro-Weld', title: 'Machines that grow with you', sub: 'We focus on practical solutions, durability and a perfect fit to the client’s needs.',
      items: [
        { title: 'In-house engineering', desc: 'Machines designed from scratch by experienced engineers from the agri sector.' },
        { title: 'Built around you', desc: 'Every machine is adapted to your line, your produce and your floor layout.' },
        { title: 'Quality & safety', desc: 'Durable materials, optional stainless steel and proven safety systems.' },
        { title: 'Complete lines', desc: 'From reception to palletising — modular, for any production scale.' },
      ],
    },
    featured: { eyebrow: 'Selected machines', title: 'Proven designs from our range', sub: 'The most frequently chosen machines for cleaning, sorting and packing.' },
    catalog: { eyebrow: 'Full range', title: 'A machine for every stage', sub: 'Browse the range by stage of the processing line.' },
    lines: { eyebrow: 'Production lines', title: 'Complete turnkey lines', body: 'We design and build cleaning, handling, sorting and packing lines — for farms, processing plants and industry. A modular build lets the line grow with your production.', points: ['Modular, scalable build', 'Agriculture · processing · industry', 'INOX builds, automation and service'], cta: 'Let’s talk about your line' },
    contact: {
      eyebrow: 'Contact', title: 'Request a quote', sub: 'Tell us what you process and at what scale — we’ll propose a machine or a full line.',
      name: 'Full name', company: 'Company / farm', email: 'E-mail', phone: 'Phone', message: 'What do you need?', submit: 'Send inquiry',
      infoTitle: 'Contact details', addrL: 'Address', phoneL: 'Phone', emailL: 'E-mail', hoursL: 'Opening hours', hours: 'Mon–Fri 7:00–16:00', note: 'The inquiry is non-binding. We usually reply within one business day.',
    },
    footer: { tagline: 'Polish manufacturer of machines and processing lines — cleaning, sorting, handling and packing for agriculture, food processing and industry.', col1: 'Navigation', col2: 'Line stages', col3: 'Contact', rights: 'All rights reserved.' },
    offer: { eyebrow: 'Machines', title: 'Machine catalog', sub: 'A full overview of Agro-Weld machines, grouped by stage of the processing line.', count: 'machines' },
    product: { back: 'Back to machines', specsTitle: 'Technical data', featTitle: 'Key features', optTitle: 'Equipment & options', modelsTitle: 'Available models', inquiryTitle: 'Interested in this machine?', inquirySub: 'We’ll configure it for your produce and production scale.', related: 'See also', model: 'Model' },
  },
  de: {
    nav: { home: 'Start', offer: 'Maschinen', process: 'Prozess', why: 'Warum wir', projects: 'Linien', contact: 'Kontakt' },
    cta: { askOffer: 'Angebot anfragen', viewMachines: 'Maschinen ansehen', viewAll: 'Gesamter Maschinenkatalog', learnMore: 'Mehr erfahren', downloadCatalog: 'Katalog (PDF) laden', backHome: 'Zurück zur Startseite', send: 'Anfrage senden' },
    hero: {
      eyebrow: 'Hersteller von Maschinen & Prozesslinien',
      titleA: 'Maschinen und Prozesslinien', titleB: 'für Landwirtschaft und Industrie',
      sub: 'Agro-Weld entwickelt und baut Maschinen zur Produktaufbereitung sowie komplette Produktionslinien — von der Annahme bis zur Palettierung. Für Landwirtschaft, Verarbeitung und Industrie.',
      s1n: '25+', s1l: 'Maschinentypen', s2n: '9', s2l: 'Linienstufen', s3n: '100%', s3l: 'nach Maß gebaut',
    },
    process: { eyebrow: 'So funktioniert es', title: 'Eine Linie, vom Feld zur Palette', sub: 'Jede Stufe der Verarbeitung decken wir mit eigenen Maschinen ab — kombiniert zu modularen, kompletten Linien.', note: 'Jede Maschine und Linie wird auf Kultur, Produktionsmenge und Hallenlayout konfiguriert.' },
    steps: [
      { name: 'Annahme', desc: 'Kistenkipper und Annahmebunker übernehmen die Ernte von Anhängern und Kisten.' },
      { name: 'Pufferung', desc: 'Pufferbunker sorgen für einen gleichmäßigen, kontinuierlichen Produktfluss.' },
      { name: 'Reinigung', desc: 'Separatoren und Bürstenreiniger entfernen Erde, Steine und Reste.' },
      { name: 'Sortierung', desc: 'Kalibrierer und Sortiertische trennen die Ware nach Größe und Qualität.' },
      { name: 'Wiegen', desc: 'Kontrollwaagen und Zähler sichern wiederholbare, genaue Portionen.' },
      { name: 'Verpacken', desc: 'Absackwaagen, Raschelmaschinen und Füller verpacken das fertige Produkt.' },
      { name: 'Palettieren', desc: 'Palettierer und Palettenformer stapeln die Verpackungen lagerfertig.' },
    ],
    why: {
      eyebrow: 'Warum Agro-Weld', title: 'Maschinen, die mit Ihnen wachsen', sub: 'Wir setzen auf praktische Lösungen, Langlebigkeit und volle Anpassung an den Kunden.',
      items: [
        { title: 'Eigene Konstruktionen', desc: 'Von erfahrenen Konstrukteuren der Agrarbranche von Grund auf entwickelt.' },
        { title: 'Auf Sie zugeschnitten', desc: 'Jede Maschine wird an Ihre Linie, Kultur und Halle angepasst.' },
        { title: 'Qualität & Sicherheit', desc: 'Langlebige Materialien, optional Edelstahl und bewährte Sicherheitssysteme.' },
        { title: 'Komplette Linien', desc: 'Von der Annahme bis zur Palettierung — modular, für jede Produktionsgröße.' },
      ],
    },
    featured: { eyebrow: 'Ausgewählte Maschinen', title: 'Bewährte Konstruktionen aus unserem Programm', sub: 'Die am häufigsten gewählten Maschinen zum Reinigen, Sortieren und Verpacken.' },
    catalog: { eyebrow: 'Gesamtes Programm', title: 'Eine Maschine für jede Stufe', sub: 'Durchsuchen Sie das Programm nach Stufe der Verarbeitungslinie.' },
    lines: { eyebrow: 'Produktionslinien', title: 'Komplette schlüsselfertige Linien', body: 'Wir planen und bauen Reinigungs-, Sortier- und Verpackungslinien — für kleine Betriebe wie für große Werke. Der modulare Aufbau lässt die Linie mit Ihrer Produktion wachsen.', points: ['Modularer, skalierbarer Aufbau', 'Landwirtschaft · Verarbeitung · Industrie', 'Edelstahl, Automatisierung und Service'], cta: 'Sprechen wir über Ihre Linie' },
    contact: {
      eyebrow: 'Kontakt', title: 'Angebot anfragen', sub: 'Sagen Sie uns, was Sie verarbeiten und in welcher Menge — wir schlagen eine Maschine oder ganze Linie vor.',
      name: 'Name', company: 'Firma / Betrieb', email: 'E-Mail', phone: 'Telefon', message: 'Was benötigen Sie?', submit: 'Anfrage senden',
      infoTitle: 'Kontaktdaten', addrL: 'Adresse', phoneL: 'Telefon', emailL: 'E-Mail', hoursL: 'Öffnungszeiten', hours: 'Mo–Fr 7:00–16:00', note: 'Die Anfrage ist unverbindlich. Wir antworten meist innerhalb eines Werktags.',
    },
    footer: { tagline: 'Polnischer Hersteller von Maschinen und Prozesslinien — Reinigen, Sortieren und Verpacken für Landwirtschaft, Verarbeitung und Industrie.', col1: 'Navigation', col2: 'Linienstufen', col3: 'Kontakt', rights: 'Alle Rechte vorbehalten.' },
    offer: { eyebrow: 'Maschinen', title: 'Maschinenkatalog', sub: 'Vollständige Übersicht der Agro-Weld-Maschinen, nach Stufe der Verarbeitungslinie gruppiert.', count: 'Maschinen' },
    product: { back: 'Zurück zu den Maschinen', specsTitle: 'Technische Daten', featTitle: 'Wichtigste Merkmale', optTitle: 'Ausstattung & Optionen', modelsTitle: 'Verfügbare Modelle', inquiryTitle: 'Interesse an dieser Maschine?', inquirySub: 'Wir konfigurieren sie für Ihre Kultur und Produktionsmenge.', related: 'Siehe auch', model: 'Modell' },
  },
  ru: {
    nav: { home: 'Главная', offer: 'Машины', process: 'Процесс', why: 'Почему мы', projects: 'Линии', contact: 'Контакты' },
    cta: { askOffer: 'Запросить предложение', viewMachines: 'Смотреть машины', viewAll: 'Полный каталог машин', learnMore: 'Подробнее', downloadCatalog: 'Скачать каталог (PDF)', backHome: 'На главную', send: 'Отправить запрос' },
    hero: {
      eyebrow: 'Производитель машин и техлиний',
      titleA: 'Машины и технологические линии', titleB: 'для сельского хозяйства и промышленности',
      sub: 'Agro-Weld проектирует и производит машины для обработки продукции и полные производственные линии — от приёма сырья до паллетирования. Для хозяйств, переработки и промышленности.',
      s1n: '25+', s1l: 'типов машин', s2n: '9', s2l: 'этапов линии', s3n: '100%', s3l: 'под заказ',
    },
    process: { eyebrow: 'Как это работает', title: 'Одна линия — от поля до паллеты', sub: 'Каждый этап обработки урожая мы закрываем собственными машинами, объединёнными в модульные линии.', note: 'Каждая машина и линия настраивается под культуру, объём производства и планировку цеха.' },
    steps: [
      { name: 'Приём', desc: 'Опрокидыватели ящиков и приёмные бункеры принимают урожай с прицепов и ящиков.' },
      { name: 'Буферизация', desc: 'Буферные бункеры поддерживают ровный непрерывный поток продукта.' },
      { name: 'Очистка', desc: 'Сепараторы и щёточные машины удаляют землю, камни и остатки.' },
      { name: 'Сортировка', desc: 'Калибровщики и сортировочные столы делят продукт по размеру и качеству.' },
      { name: 'Взвешивание', desc: 'Контрольные весы и счётчики обеспечивают точные повторяемые порции.' },
      { name: 'Упаковка', desc: 'Весовые упаковщики, машины рашель и наполнители фасуют готовый продукт.' },
      { name: 'Паллетирование', desc: 'Паллетайзеры и формирователи укладывают упаковки на паллету.' },
    ],
    why: {
      eyebrow: 'Почему Agro-Weld', title: 'Машины, которые растут вместе с вами', sub: 'Делаем ставку на практичные решения, надёжность и полную адаптацию под клиента.',
      items: [
        { title: 'Собственные конструкции', desc: 'Машины разработаны с нуля опытными конструкторами из аграрной отрасли.' },
        { title: 'Под вас', desc: 'Каждая машина адаптируется под вашу линию, продукт и планировку цеха.' },
        { title: 'Качество и безопасность', desc: 'Прочные материалы, опция нержавеющей стали и проверенные системы защиты.' },
        { title: 'Полные линии', desc: 'От приёма до паллетирования — модульно, под любой объём производства.' },
      ],
    },
    featured: { eyebrow: 'Избранные машины', title: 'Проверенные конструкции из нашего ассортимента', sub: 'Чаще всего выбираемые машины для очистки, сортировки и упаковки.' },
    catalog: { eyebrow: 'Весь ассортимент', title: 'Машина для каждого этапа', sub: 'Просматривайте ассортимент по этапам технологической линии.' },
    lines: { eyebrow: 'Производственные линии', title: 'Полные линии «под ключ»', body: 'Проектируем и строим линии очистки, сортировки и упаковки — для малых хозяйств и крупных заводов. Модульная конструкция позволяет наращивать линию вместе с производством.', points: ['Модульная масштабируемая конструкция', 'Агро · переработка · промышленность', 'Нержавеющая сталь, автоматизация и сервис'], cta: 'Обсудим вашу линию' },
    contact: {
      eyebrow: 'Контакты', title: 'Запросить предложение', sub: 'Опишите, что и в каком объёме вы перерабатываете — предложим машину или целую линию.',
      name: 'Имя и фамилия', company: 'Компания / хозяйство', email: 'E-mail', phone: 'Телефон', message: 'Что вам нужно?', submit: 'Отправить запрос',
      infoTitle: 'Контактные данные', addrL: 'Адрес', phoneL: 'Телефон', emailL: 'E-mail', hoursL: 'Часы работы', hours: 'Пн–Пт 7:00–16:00', note: 'Запрос ни к чему не обязывает. Обычно отвечаем в течение одного рабочего дня.',
    },
    footer: { tagline: 'Польский производитель машин и технологических линий — очистка, сортировка и упаковка для сельского хозяйства, переработки и промышленности.', col1: 'Навигация', col2: 'Этапы линии', col3: 'Контакты', rights: 'Все права защищены.' },
    offer: { eyebrow: 'Машины', title: 'Каталог машин', sub: 'Полный обзор машин Agro-Weld, сгруппированный по этапам технологической линии.', count: 'машин' },
    product: { back: 'Назад к машинам', specsTitle: 'Технические данные', featTitle: 'Ключевые особенности', optTitle: 'Оснащение и опции', modelsTitle: 'Доступные модели', inquiryTitle: 'Заинтересовала эта машина?', inquirySub: 'Настроим её под вашу продукцию и объём производства.', related: 'Смотрите также', model: 'Модель' },
  },
  fr: {
    nav: { home: 'Accueil', offer: 'Machines', process: 'Process', why: 'Pourquoi nous', projects: 'Lignes', contact: 'Contact' },
    cta: { askOffer: 'Demander un devis', viewMachines: 'Voir les machines', viewAll: 'Catalogue complet', learnMore: 'En savoir plus', downloadCatalog: 'Télécharger le catalogue (PDF)', backHome: 'Retour à l’accueil', send: 'Envoyer la demande' },
    hero: {
      eyebrow: 'Fabricant de machines & lignes de process',
      titleA: 'Machines et lignes de process', titleB: 'pour l’agriculture et l’industrie',
      sub: 'Agro-Weld conçoit et fabrique des machines de traitement et des lignes de production complètes — de la réception à la palettisation. Pour l’agriculture, la transformation et l’industrie.',
      s1n: '25+', s1l: 'types de machines', s2n: '9', s2l: 'étapes de ligne', s3n: '100%', s3l: 'sur mesure',
    },
    process: { eyebrow: 'Comment ça marche', title: 'Une ligne, du champ à la palette', sub: 'Nous couvrons chaque étape du traitement avec nos propres machines, combinées en lignes modulaires complètes.', note: 'Chaque machine et ligne est configurée selon la culture, le volume et l’implantation de l’atelier.' },
    steps: [
      { name: 'Réception', desc: 'Basculeurs de caisses et trémies de réception reçoivent la récolte des remorques et caisses.' },
      { name: 'Tampon', desc: 'Les trémies tampon maintiennent un flux régulier et continu sur la ligne.' },
      { name: 'Nettoyage', desc: 'Séparateurs et brosseuses retirent terre, pierres et résidus.' },
      { name: 'Tri', desc: 'Calibreurs et tables de tri répartissent les produits par taille et qualité.' },
      { name: 'Pesage', desc: 'Trieuses pondérales et compteuses assurent des portions précises et répétables.' },
      { name: 'Conditionnement', desc: 'Peseuses-ensacheuses, ensacheuses raschel et remplisseurs conditionnent le produit fini.' },
      { name: 'Palettisation', desc: 'Palettiseurs et formeurs empilent les emballages prêts pour l’entrepôt.' },
    ],
    why: {
      eyebrow: 'Pourquoi Agro-Weld', title: 'Des machines qui évoluent avec vous', sub: 'Nous misons sur des solutions pratiques, la durabilité et une adaptation totale au client.',
      items: [
        { title: 'Conceptions maison', desc: 'Machines conçues de zéro par des ingénieurs expérimentés du secteur agricole.' },
        { title: 'À votre mesure', desc: 'Chaque machine s’adapte à votre ligne, vos produits et votre atelier.' },
        { title: 'Qualité & sécurité', desc: 'Matériaux durables, inox en option et systèmes de sécurité éprouvés.' },
        { title: 'Lignes complètes', desc: 'De la réception à la palettisation — modulaire, pour toute échelle.' },
      ],
    },
    featured: { eyebrow: 'Machines sélectionnées', title: 'Des conceptions éprouvées de notre gamme', sub: 'Les machines les plus choisies pour nettoyer, trier et conditionner.' },
    catalog: { eyebrow: 'Gamme complète', title: 'Une machine pour chaque étape', sub: 'Parcourez la gamme par étape de la ligne de traitement.' },
    lines: { eyebrow: 'Lignes de production', title: 'Lignes complètes clés en main', body: 'Nous concevons et construisons des lignes de nettoyage, tri et conditionnement — pour petites fermes comme grandes usines. La conception modulaire fait grandir la ligne avec votre production.', points: ['Conception modulaire et évolutive', 'Agriculture · transformation · industrie', 'Inox, automatisation et service'], cta: 'Parlons de votre ligne' },
    contact: {
      eyebrow: 'Contact', title: 'Demander un devis', sub: 'Dites-nous ce que vous traitez et à quelle échelle — nous proposerons une machine ou une ligne entière.',
      name: 'Nom et prénom', company: 'Société / exploitation', email: 'E-mail', phone: 'Téléphone', message: 'De quoi avez-vous besoin ?', submit: 'Envoyer la demande',
      infoTitle: 'Coordonnées', addrL: 'Adresse', phoneL: 'Téléphone', emailL: 'E-mail', hoursL: 'Horaires', hours: 'Lun–Ven 7:00–16:00', note: 'La demande est sans engagement. Nous répondons généralement sous un jour ouvré.',
    },
    footer: { tagline: 'Fabricant polonais de machines et de lignes de process — nettoyage, tri et conditionnement pour l’agriculture, la transformation et l’industrie.', col1: 'Navigation', col2: 'Étapes de ligne', col3: 'Contact', rights: 'Tous droits réservés.' },
    offer: { eyebrow: 'Machines', title: 'Catalogue de machines', sub: 'Un aperçu complet des machines Agro-Weld, regroupées par étape de la ligne de traitement.', count: 'machines' },
    product: { back: 'Retour aux machines', specsTitle: 'Données techniques', featTitle: 'Caractéristiques clés', optTitle: 'Équipement & options', modelsTitle: 'Modèles disponibles', inquiryTitle: 'Cette machine vous intéresse ?', inquirySub: 'Nous la configurons selon vos produits et votre échelle.', related: 'Voir aussi', model: 'Modèle' },
  },
};

const CATEGORIES = [
  { id: 'unload', slug: 'rozladunek-skrzyn', name: { pl: 'Rozładunek skrzyń', en: 'Crate unloading', de: 'Kistenentladung', ru: 'Разгрузка ящиков', fr: 'Déchargement' } },
  { id: 'reception', slug: 'przyjecie-i-buforowanie', name: { pl: 'Przyjęcie i buforowanie', en: 'Reception & buffering', de: 'Annahme & Pufferung', ru: 'Приём и буферизация', fr: 'Réception & tampon' } },
  { id: 'cleaning', slug: 'oczyszczanie', name: { pl: 'Oczyszczanie', en: 'Cleaning', de: 'Reinigung', ru: 'Очистка', fr: 'Nettoyage' } },
  { id: 'sorting', slug: 'sortowanie', name: { pl: 'Sortowanie', en: 'Sorting & grading', de: 'Sortierung', ru: 'Сортировка', fr: 'Tri & calibrage' } },
  { id: 'selection', slug: 'selekcja', name: { pl: 'Selekcja', en: 'Selection', de: 'Selektion', ru: 'Селекция', fr: 'Sélection' } },
  { id: 'weighing', slug: 'wazenie', name: { pl: 'Ważenie', en: 'Weighing & counting', de: 'Wiegen & Zählen', ru: 'Взвешивание и счёт', fr: 'Pesage & comptage' } },
  { id: 'packing', slug: 'pakowanie', name: { pl: 'Pakowanie', en: 'Packing', de: 'Verpackung', ru: 'Упаковка', fr: 'Conditionnement' } },
  { id: 'palletising', slug: 'paletyzacja', name: { pl: 'Paletyzacja', en: 'Palletising', de: 'Palettierung', ru: 'Паллетирование', fr: 'Palettisation' } },
  { id: 'conveyors', slug: 'przenosniki-tasmowe', name: { pl: 'Przenośniki taśmowe', en: 'Conveyors', de: 'Förderer', ru: 'Конвейеры', fr: 'Convoyeurs' } },
  { id: 'weeding', slug: 'pielenie', name: { pl: 'Pielenie', en: 'Weeding', de: 'Hacken', ru: 'Прополка', fr: 'Désherbage' } },
];

const M = (id, cat, img, models, name, short) => ({ id, cat, img, models, name, short });
const MACHINES = [
  M('wywrotnica', 'unload', null, 'WS-1420 · WS-1620 · WS-1820',
    { pl: 'Wywrotnica skrzyniopalet', en: 'Pallet-box tipper', de: 'Kistenkipper', ru: 'Опрокидыватель ящиков', fr: 'Basculeur de caisses' },
    { pl: 'Rozładowuje towar ze skrzyń do koszy; udźwig do 2 ton i bezpieczne siłowniki.', en: 'Empties produce from crates into hoppers; up to 2 t with safety cylinders.', de: 'Entleert Ware aus Kisten in Bunker; bis 2 t mit Sicherheitszylindern.', ru: 'Выгружает продукт из ящиков в бункеры; до 2 т, безопасные цилиндры.', fr: 'Vide la récolte des caisses vers les trémies; jusqu’à 2 t, vérins sécurisés.' }),
  M('kosz', 'reception', 'assets/kp5000.webp', 'KP1000 – KP5000G',
    { pl: 'Kosz przyjęciowy', en: 'Receiving hopper', de: 'Annahmebunker', ru: 'Приёмный бункер', fr: 'Trémie de réception' },
    { pl: 'Przyjmuje plon z przyczep i podaje go na linię; pojemność od 1 do 5 m³.', en: 'Takes produce from trailers and feeds the line; 1 to 5 m³ capacity.', de: 'Nimmt Ernte vom Anhänger und beschickt die Linie; 1 bis 5 m³.', ru: 'Принимает урожай с прицепов и подаёт на линию; объём 1–5 м³.', fr: 'Reçoit la récolte des remorques et alimente la ligne; 1 à 5 m³.' }),
  M('zasobnik', 'reception', null, '1,5 – 24 m³',
    { pl: 'Zasobnik buforowy', en: 'Buffer hopper', de: 'Pufferbunker', ru: 'Буферный бункер', fr: 'Trémie tampon' },
    { pl: 'Utrzymuje równy przepływ towaru; rozbudowywany nadstawkami, montaż do podłoża.', en: 'Keeps an even product flow; expandable with extensions, floor-mountable.', de: 'Hält gleichmäßigen Produktfluss; mit Aufsätzen erweiterbar, bodenmontierbar.', ru: 'Поддерживает ровный поток; расширяется надставками, крепится к полу.', fr: 'Maintient un flux régulier; extensible par rehausses, fixable au sol.' }),
  M('separator', 'cleaning', null, 'SE-560 · SE-880 · SE-1080',
    { pl: 'Separator ziemi i kamieni', en: 'Soil & stone separator', de: 'Erd- und Steinseparator', ru: 'Сепаратор земли и камней', fr: 'Séparateur terre & pierres' },
    { pl: 'Usuwa ziemię, kamienie i natkę gwiaździstymi wałkami; wydajność do 10 t/h.', en: 'Removes soil, stones and tops with star rollers; up to 10 t/h.', de: 'Entfernt Erde, Steine und Kraut mit Sternwalzen; bis 10 t/h.', ru: 'Удаляет землю, камни и ботву звёздчатыми валами; до 10 т/ч.', fr: 'Retire terre, pierres et fanes par rouleaux étoilés; jusqu’à 10 t/h.' }),
  M('czyszczarka', 'cleaning', 'assets/czyszczarka-docisk.webp', 'CS1056 · CS1480 · CS20110',
    { pl: 'Czyszczarka szczotkowa', en: 'Brush cleaner', de: 'Bürstenreiniger', ru: 'Щёточная чистка', fr: 'Brosseuse de nettoyage' },
    { pl: 'Szczotki proste lub falowane czyszczą warzywa okrągłe i podłużne.', en: 'Straight or wavy brushes clean both round and elongated vegetables.', de: 'Gerade oder gewellte Bürsten reinigen runde und längliche Gemüse.', ru: 'Прямые или волнистые щётки чистят круглые и длинные овощи.', fr: 'Brosses droites ou ondulées nettoient légumes ronds et longs.' }),
  M('czyszczarka-imbir', 'cleaning', null, 'CI-00',
    { pl: 'Czyszczarka do imbiru i chrzanu', en: 'Ginger & horseradish cleaner', de: 'Ingwer- & Meerrettich-Reiniger', ru: 'Очистка имбиря и хрена', fr: 'Nettoyeur gingembre & raifort' },
    { pl: 'Delikatnie oczyszcza kłącza i warzywa korzeniowe; wydajność 100 kg/h.', en: 'Gently cleans rhizomes and root vegetables; 100 kg/h.', de: 'Reinigt schonend Rhizome und Wurzelgemüse; 100 kg/h.', ru: 'Бережно очищает корневища и корнеплоды; 100 кг/ч.', fr: 'Nettoie délicatement rhizomes et racines; 100 kg/h.' }),
  M('wanna', 'cleaning', null, 'RA-PP-00 · WP-800 · WP-900',
    { pl: 'Wanna do płukania', en: 'Washing tank', de: 'Waschwanne', ru: 'Моечная ванна', fr: 'Bac de lavage' },
    { pl: 'Wstępne płukanie warzyw korzeniowych z perforowaną taśmą wyładowczą.', en: 'Pre-washes root vegetables with a perforated discharge belt.', de: 'Vorwäsche von Wurzelgemüse mit perforiertem Austragsband.', ru: 'Предварительная мойка корнеплодов с перфорированной лентой.', fr: 'Pré-lavage des légumes-racines avec tapis d’évacuation perforé.' }),
  M('kalibrownik', 'sorting', 'assets/kalibrownik.webp', 'KA-780 · KA-880',
    { pl: 'Kalibrownik rozsuwany', en: 'Adjustable grader', de: 'Verstellbarer Kalibrierer', ru: 'Раздвижной калибровщик', fr: 'Calibreur réglable' },
    { pl: 'Sortuje warzywa wg wielkości; rozstaw wałków regulowany korbką w kilka sekund.', en: 'Sizes vegetables; roller gap set by hand crank in seconds.', de: 'Sortiert nach Größe; Walzenabstand per Kurbel in Sekunden.', ru: 'Сортирует по размеру; зазор валов регулируется рукояткой за секунды.', fr: 'Trie par taille; écart des rouleaux réglé à la manivelle en secondes.' }),
  M('sortownik-sod', 'sorting', 'assets/real-borowka.jpg', 'SOD-6010 · 6012 · 6014',
    { pl: 'Sortownik do owoców drobnych', en: 'Small-fruit sorter', de: 'Kleinfrucht-Sortierer', ru: 'Сортировщик мелких ягод', fr: 'Trieuse petits fruits' },
    { pl: 'Delikatnie sortuje borówki i drobne owoce; boczna platforma na skrzynkę.', en: 'Gently sorts blueberries and small fruit; side crate platform.', de: 'Sortiert schonend Heidelbeeren und Kleinobst; seitliche Kistenablage.', ru: 'Бережно сортирует чернику и мелкие плоды; боковая платформа.', fr: 'Trie délicatement myrtilles et petits fruits; plateau latéral.' }),
  M('sortownik-2b', 'sorting', null, 'SO2B-601012',
    { pl: 'Dwubębnowy sortownik', en: 'Twin-drum sorter', de: 'Doppeltrommel-Sortierer', ru: 'Двухбарабанный сортировщик', fr: 'Trieuse à deux tambours' },
    { pl: 'Precyzyjne sortowanie drobnych owoców; biała taśma i oświetlenie LED.', en: 'Precise small-fruit sorting; white belt and LED lighting.', de: 'Präzises Sortieren von Kleinobst; weißes Band und LED-Licht.', ru: 'Точная сортировка мелких плодов; белая лента и LED-подсветка.', fr: 'Tri précis des petits fruits; tapis blanc et éclairage LED.' }),
  M('stol-tasmowy', 'selection', 'assets/real-inox.jpg', 'SST-2008 · 3510 · 5012',
    { pl: 'Stół selekcyjny taśmowy', en: 'Belt sorting table', de: 'Band-Sortiertisch', ru: 'Ленточный сортировочный стол', fr: 'Table de tri à bande' },
    { pl: 'Ręczna selekcja na taśmie PCV; konfigurowalne podzielnice i oświetlenie LED.', en: 'Manual selection on a PVC belt; configurable dividers and LED lighting.', de: 'Manuelle Selektion auf PVC-Band; konfigurierbare Teiler und LED.', ru: 'Ручная сортировка на ПВХ-ленте; делители и LED-подсветка.', fr: 'Tri manuel sur tapis PVC; séparateurs configurables et LED.' }),
  M('stol-rolkowy', 'selection', null, 'SSR-2508 · 3010 · 4012',
    { pl: 'Stół selekcyjny rolkowy', en: 'Roller sorting table', de: 'Rollen-Sortiertisch', ru: 'Роликовый сортировочный стол', fr: 'Table de tri à rouleaux' },
    { pl: 'Selekcja na rolkach z aluminium lub plastiku; otwarta rolka nie zapycha się.', en: 'Selection on aluminium or plastic rollers; open roller resists clogging.', de: 'Selektion auf Alu- oder Kunststoffrollen; offene Rolle verstopft nicht.', ru: 'Сортировка на алюминиевых/пластиковых роликах; не забивается.', fr: 'Tri sur rouleaux alu ou plastique; rouleau ouvert anti-bourrage.' }),
  M('liczarka', 'weighing', null, 'LO1.90 · LO2.90',
    { pl: 'Liczarka', en: 'Fruit counter', de: 'Zählmaschine', ru: 'Счётчик плодов', fr: 'Compteuse de fruits' },
    { pl: 'Precyzyjnie liczy większe owoce na sztuki; wersja jedno- lub dwurzędowa.', en: 'Counts larger fruit by piece; single- or twin-lane version.', de: 'Zählt größeres Obst stückweise; ein- oder zweispurig.', ru: 'Точно считает крупные плоды поштучно; одно- или двухрядный.', fr: 'Compte les gros fruits à l’unité; version simple ou double voie.' }),
  M('waga', 'weighing', null, 'WKO',
    { pl: 'Waga kontrolna', en: 'Checkweigher', de: 'Kontrollwaage', ru: 'Контрольные весы', fr: 'Trieuse pondérale' },
    { pl: 'Dynamicznie waży opakowania w ruchu i odrzuca te poza tolerancją.', en: 'Dynamically weighs packs in motion and rejects out-of-tolerance ones.', de: 'Wiegt Verpackungen dynamisch und schleust fehlerhafte aus.', ru: 'Динамически взвешивает упаковки и отбраковывает вне допуска.', fr: 'Pèse les emballages en mouvement et rejette les hors-tolérance.' }),
  M('wagoworkownica', 'packing', null, 'WW-302',
    { pl: 'Wagoworkownica', en: 'Weigh-bagger', de: 'Wäge-Absackmaschine', ru: 'Весовой упаковщик', fr: 'Peseuse-ensacheuse' },
    { pl: 'Dozuje i pakuje warzywa do worków; panel dotykowy 7", zakres 1–30 kg.', en: 'Doses and bags vegetables; 7" touch panel, 1–30 kg.', de: 'Dosiert und sackt Gemüse ab; 7"-Touchpanel, 1–30 kg.', ru: 'Дозирует и фасует овощи в мешки; сенсор 7", 1–30 кг.', fr: 'Dose et ensache les légumes; écran 7", 1–30 kg.' }),
  M('raszlownica', 'packing', 'assets/real-raszlownica.jpg', 'RA1 · RA2',
    { pl: 'Raszlownica', en: 'Raschel bagger', de: 'Raschelsack-Maschine', ru: 'Машина сетки-рашель', fr: 'Ensacheuse raschel' },
    { pl: 'Pakuje worki 2,5–25 kg; zaszywarki Fischbein / Newlong / Yao Han, panel 7".', en: 'Packs 2.5–25 kg bags; Fischbein/Newlong/Yao Han sewing heads.', de: 'Verpackt 2,5–25 kg Säcke; Nähköpfe Fischbein/Newlong/Yao Han.', ru: 'Фасует мешки 2,5–25 кг; швейные головки Fischbein/Newlong/Yao Han.', fr: 'Conditionne sacs 2,5–25 kg; têtes Fischbein/Newlong/Yao Han.' }),
  M('napelniacz', 'packing', null, 'NK-1 · NK-2',
    { pl: 'Napełniacz kaskadowy', en: 'Cascade filler', de: 'Kaskadenfüller', ru: 'Каскадный наполнитель', fr: 'Remplisseur à cascade' },
    { pl: 'Załadunek big-bagów i skrzyniopalet; kaskada z 9 żaglami, opcja wagi.', en: 'Fills big-bags and pallet boxes; 9-flap cascade, optional scale.', de: 'Befüllt Big-Bags und Palettenboxen; 9-Segel-Kaskade, optional Waage.', ru: 'Загрузка биг-бэгов и ящиков; каскад из 9 створок, опц. весы.', fr: 'Remplit big-bags et caisses-palettes; cascade 9 voiles, pesée en option.' }),
  M('stol-obrotowy', 'packing', null, 'SO-150',
    { pl: 'Stół obrotowy', en: 'Rotary table', de: 'Drehtisch', ru: 'Поворотный стол', fr: 'Table rotative' },
    { pl: 'Buforuje i kompletuje produkt na końcu linii; rewers i regulacja prędkości.', en: 'Buffers and collates product at line end; reverse and speed control.', de: 'Puffert und sammelt Produkt am Linienende; Reversierung und Drehzahl.', ru: 'Буферизует и комплектует продукт в конце линии; реверс и регулировка.', fr: 'Tamponne et regroupe en fin de ligne; inversion et réglage de vitesse.' }),
  M('bufor', 'packing', null, 'BU-12 · BU-20',
    { pl: 'Bufor do pakowania', en: 'Packing buffer', de: 'Verpackungspuffer', ru: 'Упаковочный буфер', fr: 'Tampon d’emballage' },
    { pl: 'Ręczna selekcja i pakowanie do skrzyń; podest z opcją wagi, 1–2 stanowiska.', en: 'Manual selection and crate packing; platform with optional scale.', de: 'Manuelle Selektion und Kistenpackung; Podest mit Waage-Option.', ru: 'Ручная сортировка и упаковка в ящики; платформа с опц. весами.', fr: 'Tri manuel et mise en caisses; plateau avec pesée en option.' }),
  M('paletyzator', 'palletising', null, 'Verbruggen VPM',
    { pl: 'Paletyzatory Verbruggen', en: 'Verbruggen palletisers', de: 'Verbruggen-Palettierer', ru: 'Паллетайзеры Verbruggen', fr: 'Palettiseurs Verbruggen' },
    { pl: 'Automatyczne układanie worków, skrzynek i kartonów na palecie.', en: 'Automatic stacking of bags, crates and cartons on pallets.', de: 'Automatisches Stapeln von Säcken, Kisten und Kartons.', ru: 'Автоматическая укладка мешков, ящиков и коробов на паллету.', fr: 'Empilage automatique de sacs, caisses et cartons sur palette.' }),
  M('formator', 'palletising', 'assets/formator.png', 'FP-1280 · FP-1210',
    { pl: 'Formator palet', en: 'Pallet former', de: 'Palettenformer', ru: 'Формирователь паллет', fr: 'Formeur de palette' },
    { pl: 'Optymalizuje układanie worków na palecie euro lub przemysłowej; składane ściany.', en: 'Optimises bag stacking on euro or industrial pallets; folding walls.', de: 'Optimiert Sackstapelung auf Euro- oder Industriepaletten; klappbare Wände.', ru: 'Оптимизирует укладку мешков на евро/пром. паллету; складные стенки.', fr: 'Optimise l’empilage sur palette euro ou industrielle; parois pliantes.' }),
  M('przenosnik', 'conveyors', 'assets/wanna.png', 'szer. 20–90 cm · dł. 1–12 m',
    { pl: 'Przenośniki taśmowe i rolkowe', en: 'Belt & roller conveyors', de: 'Band- & Rollenförderer', ru: 'Ленточные и роликовые конвейеры', fr: 'Convoyeurs à bande & rouleaux' },
    { pl: 'Taśmowe, rolkowe i modularne; kąt wznosu do 50°, taśmy z atestem.', en: 'Belt, roller and modular; up to 50° incline, food-grade belts.', de: 'Band, Rolle und Modulband; bis 50° Steigung, lebensmittelecht.', ru: 'Ленточные, роликовые, модульные; до 50°, пищевые ленты.', fr: 'Bande, rouleaux et modulaire; jusqu’à 50°, bandes alimentaires.' }),
  M('przenosnik-poprzeczny', 'conveyors', 'assets/przenosnik-poprzeczny.png', 'RA-PP-00',
    { pl: 'Przenośnik poprzeczny', en: 'Cross conveyor', de: 'Querförderer', ru: 'Поперечный конвейер', fr: 'Convoyeur transversal' },
    { pl: 'Podaje porcje warzyw do raszlownicy; taśma z amortyzującymi zabierakami.', en: 'Feeds vegetable portions to the bagger; belt with cushioning cleats.', de: 'Führt Gemüseportionen zur Absackmaschine; Band mit dämpfenden Mitnehmern.', ru: 'Подаёт порции овощей к упаковщику; лента с амортизирующими планками.', fr: 'Achemine les portions vers l’ensacheuse; tapis à taquets amortisseurs.' }),
  M('pielnik', 'weeding', null, 'Pip-4 · Pia-4',
    { pl: 'Pielnik do obróbki redlin', en: 'Inter-row weeder', de: 'Hackgerät für Dämme', ru: 'Культиватор для гребней', fr: 'Bineuse pour buttes' },
    { pl: 'Mechaniczne odchwaszczanie międzyrzędzi i formowanie redlin; sekcje na równoległoboku.', en: 'Mechanical inter-row weeding and ridge forming; parallelogram sections.', de: 'Mechanische Reihenhacke und Dammformung; Parallelogramm-Sektionen.', ru: 'Механическая прополка междурядий и формирование гребней.', fr: 'Désherbage mécanique inter-rangs et formation de buttes.' }),
];


// SEO: czyste slugi URL dla stron produktowych (/maszyny/{slug}/)
const MACHINE_SLUGS = {
  'wywrotnica': 'wywrotnica-skrzyniopalet',
  'kosz': 'kosz-przyjeciowy',
  'zasobnik': 'zasobnik-buforowy',
  'separator': 'separator-ziemi-i-kamieni',
  'czyszczarka': 'czyszczarka-szczotkowa',
  'czyszczarka-imbir': 'czyszczarka-do-imbiru-i-chrzanu',
  'wanna': 'wanna-do-plukania',
  'kalibrownik': 'kalibrownik-rozsuwany',
  'sortownik-sod': 'sortownik-do-owocow-drobnych',
  'sortownik-2b': 'dwubebnowy-sortownik',
  'stol-tasmowy': 'stol-selekcyjny-tasmowy',
  'stol-rolkowy': 'stol-selekcyjny-rolkowy',
  'liczarka': 'liczarka-do-owocow',
  'waga': 'waga-kontrolna',
  'wagoworkownica': 'wagoworkownica',
  'raszlownica': 'raszlownica',
  'napelniacz': 'napelniacz-kaskadowy',
  'stol-obrotowy': 'stol-obrotowy',
  'bufor': 'bufor-do-pakowania',
  'paletyzator': 'paletyzatory-verbruggen',
  'formator': 'formator-palet',
  'przenosnik': 'przenosniki-tasmowe-i-rolkowe',
  'przenosnik-poprzeczny': 'przenosnik-poprzeczny',
  'pielnik': 'pielnik-do-obrobki-redlin',
};
MACHINES.forEach((m) => { m.slug = MACHINE_SLUGS[m.id]; });

const FEATURED = ['kosz', 'czyszczarka', 'kalibrownik', 'przenosnik-poprzeczny', 'przenosnik', 'formator'];

const CONTACT = {
  company: 'Agro-Weld Spółka z ograniczoną odpowiedzialnością',
  address: 'ul. Prądzyńskiego 16, Środa Wlkp.',
  email: 'biuro@agro-weld.pl',
  phone1: '+48 725 140 257',
  phone2: '+48 608 230 369',
  www: 'www.agro-weld.pl',
};

export default { LANGS, UI, CATEGORIES, MACHINES, FEATURED, CONTACT };
