
globalThis.BASE = 'https://www.agro-weld.pl';
globalThis.MONO = "font-family:'Space Mono',monospace";
globalThis.DF = "font-family:'Bricolage Grotesque',Arial,sans-serif";
globalThis.FONTS = '<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:wght@400;600;700;800&family=Space+Mono:wght@400;700&display=swap" rel="stylesheet">';
globalThis.header = function(R){
  return '<header style="background:#14160E;border-bottom:1px solid rgba(236,231,215,.14)"><div style="max-width:1280px;margin:0 auto;padding:16px 32px;display:flex;align-items:center;justify-content:space-between;gap:24px"><a href="'+R+'Strona-glowna.dc.html" style="display:flex;align-items:center;gap:12px;text-decoration:none"><img src="'+R+'assets/logo.webp" alt="Agro-Weld — logo producenta maszyn rolniczych" style="height:34px;width:auto;display:block"></a><nav style="display:flex;align-items:center;gap:26px;'+MONO+';font-size:12.5px;letter-spacing:.06em"><a href="'+R+'Strona-glowna.dc.html" style="color:#C3C8AF;text-decoration:none">Start</a><a href="'+R+'maszyny/index.html" style="color:#ECE7D7;text-decoration:none;font-weight:700">Maszyny</a><a href="'+R+'Strona-glowna.dc.html#linie" style="color:#C3C8AF;text-decoration:none">Linie</a><a href="'+R+'Strona-glowna.dc.html#kontakt" style="color:#B7D44B;text-decoration:none;font-weight:700">Kontakt</a></nav></div></header>';
};
globalThis.footer = function(R){
  return '<footer style="background:#14160E;color:#A7AE92"><div style="max-width:1280px;margin:0 auto;padding:44px 32px;display:flex;flex-wrap:wrap;gap:32px;justify-content:space-between;align-items:flex-start"><div style="max-width:380px"><div style="'+DF+';font-size:19px;font-weight:700;color:#ECE7D7;margin-bottom:10px">Agro-Weld Spółka z ograniczoną odpowiedzialnością</div><p style="font-size:14px;line-height:1.6;margin:0">Polski producent maszyn do czyszczenia, sortowania i pakowania warzyw i owoców.</p></div><div style="'+MONO+';font-size:12.5px;line-height:2">ul. Prądzyńskiego 16, Środa Wlkp.<br><a href="tel:+48725140257" style="color:#B7D44B;text-decoration:none">+48 725 140 257</a><br><a href="mailto:biuro@agro-weld.pl" style="color:#B7D44B;text-decoration:none">biuro@agro-weld.pl</a></div></div><div style="max-width:1280px;margin:0 auto;padding:14px 32px;border-top:1px solid rgba(236,231,215,.1);'+MONO+';font-size:11px;letter-spacing:.08em;color:#5E6A47;display:flex;justify-content:space-between;gap:16px;flex-wrap:wrap"><span>© 2026 Agro-Weld. Wszelkie prawa zastrzeżone.</span><span>agro-weld.pl</span></div></footer>';
};
globalThis.rail = function(left, right){
  return '<div style="display:flex;align-items:center;justify-content:space-between;gap:20px;border-top:1px solid rgba(20,22,14,.18);padding-top:14px;margin-bottom:34px;'+MONO+';font-size:11px;font-weight:700;letter-spacing:.16em;text-transform:uppercase"><span style="color:#8C3A43">'+left+'</span><span style="color:#8A8163">'+right+'</span></div>';
};
globalThis.crumb = function(R, parts){
  return '<nav aria-label="breadcrumb" style="'+MONO+';font-size:12px;color:#8A8163;margin-bottom:26px">'+parts.map(function(p){return p.href?('<a href="'+p.href+'" style="color:#41571F;text-decoration:none">'+p.t+'</a>'):('<span style="color:#14160E;font-weight:700">'+p.t+'</span>');}).join(' <span style="color:#8C3A43">/</span> ')+'</nav>';
};
globalThis.shell = function(o){
  return '<!DOCTYPE html>\n<html lang="pl">\n<head>\n<meta charset="utf-8">\n<meta name="viewport" content="width=device-width, initial-scale=1">\n<title>'+o.title+'</title>\n<meta name="description" content="'+o.meta+'">\n<link rel="canonical" href="'+o.canonical+'">\n<meta property="og:title" content="'+o.title+'">\n<meta property="og:description" content="'+o.meta+'">\n<meta property="og:type" content="website">\n<meta property="og:url" content="'+o.canonical+'">\n'+FONTS+'\n'+(o.jsonld?('<script type="application/ld+json">'+JSON.stringify(o.jsonld)+'</'+'script>'):'')+'\n<style>*{margin:0;padding:0;box-sizing:border-box}a{color:#41571F}a:hover{color:#8C3A43}body{'+DF+';background:#ECE7D7;color:#14160E;-webkit-font-smoothing:antialiased}img{max-width:100%}</style>\n</head>\n<body>\n'+o.body+'\n</body>\n</html>';
};
globalThis.productCard = function(p, R){
  var img = p.img ? R+'assets/'+p.img : R+'assets/maszyna-placeholder.png';
  var alt = p.img ? (p.imgType==='photo' ? (p.name+' Agro-Weld — realizacja u klienta') : (p.name+' '+p.models+' — maszyna Agro-Weld')) : (p.name+' — zdjęcie w przygotowaniu');
  return '<a href="'+R+'maszyny/'+p.slug+'/index.html" style="display:flex;flex-direction:column;text-decoration:none;color:#14160E;background:#ECE7D7"><div style="height:200px;background:#F1ECDF;border-bottom:1px solid #14160E;display:flex;align-items:center;justify-content:center;overflow:hidden"><img src="'+img+'" alt="'+alt+'" loading="lazy" style="max-width:86%;max-height:86%;object-fit:contain;display:block"></div><div style="padding:18px 20px 20px;flex:1;display:flex;flex-direction:column"><div style="margin-bottom:11px;'+MONO+';font-size:11px;letter-spacing:.05em"><span style="color:#8C3A43;font-weight:700">'+p.models+'</span></div><h3 style="font-size:21px;font-weight:700;letter-spacing:-.01em;line-height:1.12;margin-bottom:9px">'+p.name+'</h3><p style="font-size:14px;line-height:1.5;color:#56603F">'+p.short+'</p></div></a>';
};
globalThis.grid = function(items, R){
  return '<div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(300px,1fr));gap:1px;background:#14160E;border:1px solid #14160E">'+items.map(function(p){return productCard(p,R);}).join('')+'</div>';
};
globalThis.ctaPanel = function(R){
  return '<div style="margin-top:52px;background:linear-gradient(165deg,#243015,#1A2110);padding:38px 40px;display:flex;align-items:center;justify-content:space-between;gap:28px;flex-wrap:wrap"><div><h2 style="font-size:26px;font-weight:700;color:#fff;margin-bottom:8px">Nie wiesz, która maszyna będzie odpowiednia?</h2><p style="font-size:15px;line-height:1.6;color:#A7AE92;max-width:520px">Opisz, co przetwarzasz i w jakiej skali — doradzimy konfigurację i przygotujemy ofertę.</p></div><a href="'+R+'Strona-glowna.dc.html#kontakt" style="background:#ECE7D7;color:#14160E;text-decoration:none;padding:15px 26px;font-weight:700;font-size:15px">Zapytaj o ofertę ↗</a></div>';
};
